// Auto-generated by Guing — do not edit manually
import tokens from './tokens.json';
import type { DesignTokens } from './types';

export const designTokens: DesignTokens = tokens as DesignTokens;
export type { ColorToken, TypographyToken, DesignTokens } from './types';
